# Generated by Django 2.2.6 on 2019-11-03 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fast_food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(verbose_name=range(0, 5))),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurantcategories',
            name='category',
        ),
        migrations.RemoveField(
            model_name='restaurantcategories',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.CharField(default='www.com', max_length=100, verbose_name='Restaurant website'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='RestaurantCategories',
        ),
        migrations.AddField(
            model_name='rating',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fast_food.Restaurant'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
